{
 "title": "MarlinLoki",
 "description": "Dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Marlin Beacon Server",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", unit=\"marlin-server.service\"}"
    }
   ]
  },
  {
   "title": "Marlin Beacon Server \"$searchable_pattern\"",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"systemd-journal\", unit=\"marlin-server.service\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Marlin Relay",
   "type": "logs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", unit=\"marlin-relay.service\"}"
    }
   ]
  },
  {
   "title": "Live log of all systemd instances",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\"} |~ \"(?i)$searchable_pattern\""
    }
   ]
  },
  {
   "title": "Total stderr/stdout count",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"systemd-journal\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total $searchable_pattern rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({job=\"systemd-journal\"} |~ \"(?i)$searchable_pattern\")[30s]))"
    }
   ]
  },
  {
   "title": " Matched \"$searchable_pattern\" history",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"systemd-journal\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Total stderr/stdout count history",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"systemd-journal\"})[$__interval])) by (stream)"
    }
   ]
  }
 ]
}